version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: nika123
      POSTGRES_DB: learning
    networks:
      - freecodecamp
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: nika123
      POSTGRES_DB: learning
    networks:
      - freecodecamp
networks:
  freecodecamp:  